<a href="https://colab.research.google.com/github/EndangSupriyadi/GCI_GLOBAL_2025/blob/master/hw9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 9: Unsupervised Learning

## Question

The task will use a dataset [1] on quality of Portuguese "Vinho Verde" red wine. The dataset consists of 12 columns describing each wine sample's features (pH, acidity, etc.) and 1 column rating the wine quality ranging from 1 to 10.

Both the [dataset itself](http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv) and its [description](https://archive.ics.uci.edu/dataset/186/wine+quality) are available online.

Your task is to implement a function, `homework()`, that
1. Load the dataset
2. Apply standardization (scale the features so that they have mean of 0 and standard deviance of 1)
3. Cluster the data into `n` clusters using `KMeans`, using `init="k-means++"` and random state of 0.
4. Return the number of elements contained in each cluster, sorted in the order of the cluster label (cluster #1, cluster #2, ...).

**Expected Output:**
```python
print(homework(path_to_dataset, n=3))
> array([400, 794, 405])

print(homework(path_to_dataset, n=10))
> array([130, 235, 291,  44, 268,  28, 128, 157, 151, 167])

```


**Submission Guidelines:**<br>
When submitting your solution, only submit the entire `homework()` function. Submit by selecting this week's assignment in the Omnicampus homework section, pasting the function into the submission area, and then clicking [Submit Python Code].

Please pay attention to the following points when submitting.
- Erase the `!!WRITE ME!!` when submitting
- The return value of the function should be type `np.array[int]`
- Write your answer as one function

## Deadline
Wed, 3 Dec, 20:00 JST

## 1. Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

## 2. Downloading the Dataset
We will download the dataset using `wget` command.

In [2]:
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

--2025-12-02 07:26:02--  http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘winequality-red.csv’

winequality-red.csv     [ <=>                ]  82.23K  --.-KB/s    in 0.06s   

2025-12-02 07:26:02 (1.36 MB/s) - ‘winequality-red.csv’ saved [84199]



In [3]:
path_winequality_data = './winequality-red.csv'

You can now load the dataset using

```python
pd.read_csv('./winequality-red.csv', sep=';')
```

## 3. Solution

Please complete the following function and submit it to Omnicampus.

In [4]:
# Only the homework function within this cell should be submitted to Omnicampus
def homework(path_winequality_data, n):
    df = pd.read_csv(path_winequality_data, sep=';')
    X = df.values  # gunakan semua kolom, termasuk 'quality'
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    kmeans = KMeans(n_clusters=n, init="k-means++", random_state=0)
    labels = kmeans.fit_predict(X_scaled)
    my_result = np.bincount(labels, minlength=n).astype(int)
    return my_result


In [5]:
# Feel free to use this code block for testing
n = 10  # Set to any positive integer

homework(path_winequality_data, n)

array([147, 272, 121, 209, 159,  27,  43, 165, 188, 268])

Once you've finished checking, copy and paste your `homework()` function to Omnicampus and submit your solution. If you see a `1.0`, it means that the your answer was correct.

### References

[1] Cortez P, Cerdeira A, Almeida F, Matos T, Reis J. Wine Quality [dataset]. 2009. UCI Machine Learning Repository. Available from: https://doi.org/10.24432/C56S3T.